#!/usr/bin/env python3
"""Generate index.motion.json -- declared motion intent, checked by
`hyperframes check` against the SAME seeked timeline the renderer drives.

Rules (ported from ectoin, verified against 0.8.22's validator; flat form
with an explicit `kind`, never the nested {"appearsBy": {...}} form):
  1. ONE sidecar, at the project root.
  2. `keepsMoving` is scoped to #root, never to a scene.
  3. `maxStaticSec` is this rebuild's static ceiling: 2.0s.
  4. Assertions name COPY elements, not containers; `bySec` is ROOT-absolute
     and bound to the word the copy answers to (motion.MOTION[cid]["copy"]).
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
from timing import walk, Ctx
from motion import MOTION

STATIC_CEILING_S = 2.0
BEFORE = [("#hook-slam .kt-word", "#promise-q .kt-word"),
          ("#promise-q .kt-word", "#ev-n"),
          ("#ev-n", "#stops .kt-word"),
          ("#stops .kt-word", "#rank-1")]
STAYS = ["#stops .kt-word", "#rank-1", "#end-line"]


def main():
    units, files, total, m = walk()
    asserts = []
    for u in units:
        for sel, (fn, word, occ, slack) in MOTION[u.cid].get("copy", {}).items():
            ctx = Ctx(u)
            t = (ctx.w_abs if fn == "w" else ctx.we_abs)(word, occ)
            asserts.append({"kind": "appearsBy", "selector": sel,
                            "bySec": round(t + slack, 2),
                            "note": f"{u.cid}: bound to {fn}({word},{occ}) + {slack}s"})
    for a, b in BEFORE:
        asserts.append({"kind": "before", "a": a, "b": b})
    for sel in STAYS:
        asserts.append({"kind": "staysInFrame", "selector": sel})
    asserts.append({"kind": "keepsMoving", "withinSelector": "#root",
                    "maxStaticSec": STATIC_CEILING_S,
                    "note": "root-scoped: a per-scene selector reports off-screen time as frozen"})
    spec = {"version": 1,
            "$comment": "Generated by scripts/build_motion.py -- do not hand-edit. "
                        "`hyperframes check` discovers this file automatically."
                        + (" VO MANIFEST: FAKE -- not for delivery." if m.get("source") == "fake" else ""),
            "duration": total, "assertions": asserts}
    (ROOT / "index.motion.json").write_text(json.dumps(spec, indent=2) + "\n")
    print(f"index.motion.json: {len(asserts)} assertions "
          f"({sum(1 for a in asserts if a['kind']=='appearsBy')} appearsBy, "
          f"{len(BEFORE)} before, {len(STAYS)} staysInFrame, 1 keepsMoving @ {STATIC_CEILING_S}s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
