#!/usr/bin/env python3
"""Emit SCRIPT.md from vo_lines.py + the measured manifest. GENERATED."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from timing import walk, LEAD_KEEP
from vo_lines import NARRATOR, TEXT, CITES, CLAIMS, BLOCKS
from motion import MOTION


def mmss(t):
    return f"{int(t // 60)}:{t % 60:05.2f}"


def main():
    units, files, total, m = walk()
    fake = m.get("source") == "fake"
    words = sum(len(u.words) for u in units)
    out = ["# Script — You Bought Collagen. Where Did It Actually Go?", "",
           "<!-- GENERATED by scripts/build_script_md.py from scripts/vo_lines.py and "
           "assets/voice/master.words.json. Edit those, not this. -->", ""]
    if fake:
        out += ["> **VO MANIFEST: FAKE** — synthetic 170 wpm timing; not for delivery.", ""]
    out += [f"Single narrator — **Kimberly** `{NARRATOR[1]}` ({NARRATOR[0]}), Higgsfield `seed_audio`, "
            f"one master take ({', '.join(b for b, _ in BLOCKS)}).  ",
            f"{words} words · {m.get('wpm')} wpm overall · tempo {m.get('tempo')} · "
            f"first word at {LEAD_KEEP:.2f}s · runtime {mmss(total)} ({total:.3f}s).", "",
            "TTS-safe copy: no em-dashes, no colons, numbers spelled out. The spoken text below "
            "is the exact TTS input; on-screen beats are curated (≤ 10 words), never a transcript.", ""]
    for u in units:
        out.append(f"## {u.i + 1:02d} · `{u.cid}` — {mmss(u.start)} → {mmss(u.start + u.own)} "
                   f"({u.own:.2f}s · in: {u.kind_in or 'start'} · file `{u.file}`)")
        out.append("")
        if u.spoken:
            out.append(f"> {TEXT[u.cid]}")
            out.append("")
            out.append(f"*{len(u.words)} words · first word {mmss(u.first_word_abs)} · "
                       f"last word {mmss(u.last_word_abs)}*  ")
        else:
            out.append("*(no narration — end card)*  ")
        mo = MOTION[u.cid]
        out.append(f"**On screen:** {' · '.join(mo['text'])}  ")
        out.append(f"**Motion:** {', '.join(mo['treatments'])}  ")
        if u.cid in CLAIMS:
            out.append(f"**Claims:** {', '.join(CLAIMS[u.cid])}"
                       + (f" · **chips:** {' / '.join(CITES[u.cid])}" if u.cid in CITES else "") + "  ")
        out.append("")
    (ROOT / "SCRIPT.md").write_text("\n".join(out))
    print(f"  SCRIPT.md: {len(units)} units, {words} words, {mmss(total)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
