#!/usr/bin/env python3
"""Emit SCRIPT.md from vo_lines.py + the real scene timings. GENERATED.

vo_lines.LINES is the single source of truth -- it is literally the text sent to
TTS. This renders it human-readable with the timings the composition actually
uses, so the doc cannot drift from the video the way a hand-kept script does.
"""
import re, subprocess
from pathlib import Path
from build_frames import scene_timing
from vo_lines import LINES, DISPLAY, VOICES, by_scene
from build_index import SCENES

ROOT = Path(__file__).resolve().parent.parent
NAMES = {"soul": "SoulHabit", "jay": "Jay"}
ACT = {"00": "Cold open", "01": "1-2 · The building, and the demolition crew",
       "02": "3 · The collagen-cream problem", "03": "4 · What happens when you drink it",
       "04": "5 · The evidence plot twist",
       "05": "6-7 · What protects collagen, and the verdict"}


def main():
    t = scene_timing()
    starts, acc = {}, 0.0
    for cid, _ in SCENES:
        starts[cid] = acc
        acc += t[cid.split("-")[0]]["dur"]
    g = by_scene()

    out = ["# SCRIPT — You Bought Collagen. Where Did It Actually Go?", "",
           "> GENERATED by `scripts/build_script_md.py` from `scripts/vo_lines.py`.",
           "> Do not hand-edit: `vo_lines.LINES` is the only text sent to TTS, and",
           "> the timings below come from the real scene table.", "",
           f"**SoulHabit** — Kimberly `{VOICES['soul'][1]}` ({VOICES['soul'][0]}), "
           f"measured 161 wpm after retime  ",
           f"**Jay** — Dylan `{VOICES['jay'][1]}` ({VOICES['jay'][0]}), "
           f"measured 152 wpm after retime", "",
           "Takes are generated at their natural pace into `assets/voice/raw/`, then",
           "derived at `atempo=1.15` by `scripts/retime_vo.py`. The raw takes are never",
           "modified, so the retime is idempotent.", ""]

    for cid, _ in SCENES:
        k = cid.split("-")[0]
        if not g[k]:
            out += [f"## ACT {ACT[k]} — `{cid}`", "",
                    f"*{starts[cid]:.2f}s – {starts[cid] + t[k]['dur']:.2f}s · "
                    f"{t[k]['dur']:.2f}s · no VO (wordless cold open)*", ""]
            continue
        out += [f"## ACT {ACT[k]} — `{cid}`", "",
                f"*{starts[cid]:.2f}s – {starts[cid] + t[k]['dur']:.2f}s · "
                f"{t[k]['dur']:.2f}s · {len(g[k])} lines*", ""]
        for ln, tim in zip(g[k], t[k]["lines"]):
            gl = starts[cid] + tim["start"]
            out += [f"### Line {ln['idx']} — {NAMES[ln['who']]}  "
                    f"*({gl:.2f}s, {tim['dur']:.2f}s)*", "",
                    "**Spoken** (the exact TTS input):", "",
                    f"> {ln['text']}", "",
                    "**On screen:** "
                    + re.sub(r"</?em>", "*", DISPLAY[ln['idx']]), ""]

    (ROOT / "SCRIPT.md").write_text("\n".join(out) + "\n")
    print(f"SCRIPT.md  {len(LINES)} lines across {len(SCENES)} scenes")


if __name__ == "__main__":
    main()
