#!/usr/bin/env python3
"""Emit STORYBOARD.md by PARSING the generated index.html. Never hand-edited.

Deriving it from the real file rather than from the scene table is the point: a
storyboard that restates the spec cannot tell you the spec drifted. Chapters are
computed from real data-start values, which is also the only way the pasteable
chapter block stays true after a re-time -- nothing in the render pipeline will
ever tell you they moved.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# scene id -> chapter title, as a PAYOFF, not a section label. A chapter may open
# inside a merged file (01-building carries two), because chapters are YouTube
# description timestamps with no engine primitive behind them.
CHAPTERS = [
    ("00-cold-open", 0.0,  "Your face is a building"),
    ("01-building",  None, None),                      # continues chapter 1
    ("01-building",  "S2", "The sun runs a demolition crew"),
    ("02-door",      0.0,  "Why collagen cream can't get in"),
    ("03-digestion", 0.0,  "Your stomach doesn't do facial delivery"),
    ("04-evidence",  0.0,  "The evidence plot twist"),
    ("05-verdict",   0.0,  "What actually protects it"),
]


def mmss(t):
    m, s = divmod(int(round(t)), 60)
    return f"{m}:{s:02d}"


def parse():
    html = (ROOT / "index.html").read_text()
    # Match the ROOT tag without assuming attribute ORDER. The HyperFrames
    # preview server rewrites this file in place, injecting `data-hf-id` as the
    # FIRST attribute -- so `<div id="root"` stopped matching and this parser
    # crashed on a file that was perfectly valid. Same lesson as the scene regex
    # below, applied one level up: parse the tag, then pull each attribute out
    # independently.
    m = re.search(r'<div\b[^>]*\bid="root"[^>]*>', html)
    if not m:
        raise SystemExit("index.html has no #root div -- run build_index.py first")
    root = m.group(0)
    meta = {k: re.search(rf'data-{k}="([^"]+)"', root).group(1)
            for k in ("duration", "width", "height", "fps")}
    scenes = []
    # Parse the tag, then pull each attribute out INDEPENDENTLY. Assuming an
    # authored attribute ORDER is how a scene-parsing regex silently returns
    # zero scenes and degrades a per-scene check into a whole-render one.
    for tag in re.findall(r'<div[^>]*class="[^"]*\bscene\b[^"]*"[^>]*>', html, re.S):
        g = lambda a: (re.search(rf'{a}="([^"]+)"', tag) or [None, None])[1]
        scenes.append({"cid": g("data-composition-id"),
                       "start": float(g("data-start")),
                       "dur": float(g("data-duration"))})
    return meta, scenes


def beats(cid):
    """Authored beat count. An AUTHORING AID ONLY -- an authored tween is not a
    rendered pixel change, and this number has been wrong in both directions
    before. check-cadence.py on the real render is what answers cadence."""
    f = ROOT / "compositions" / "frames" / f"{cid}.html"
    if not f.exists():
        return 0
    # paren-balanced would be better; this is deliberately labelled an estimate
    return len(re.findall(r'\btl\.(?:to|fromTo|from|set)\s*\(', f.read_text()))


def main():
    meta, scenes = parse()
    total = float(meta["duration"])
    by_cid = {s["cid"]: s for s in scenes}
    m, s = divmod(total, 60)

    out = ["# STORYBOARD — You Bought Collagen. Where Did It Actually Go?", "",
           "> GENERATED by `scripts/build_storyboard.py`, which parses the real",
           "> `index.html`. Do not hand-edit: a drifted storyboard stops being a",
           "> spec the moment one real timing changes.", "",
           f"**Canvas** {meta['width']}×{meta['height']} landscape · "
           f"**fps** {meta['fps']} · **duration** {int(m)}:{s:05.2f} ({total:.3f}s) · "
           f"**scenes** {len(scenes)}", "", "## Chapters", "",
           "Paste-ready. Re-derived from real `data-start` values on every build.",
           "", "```"]

    ch = []
    for cid, mark, title in CHAPTERS:
        if title is None:
            continue
        if mark == "S2":
            # chapter 2 opens inside the merged 01-building, on its S2 phase
            from build_frames import scene_timing
            t = scene_timing()["01"]["lines"][4]["start"]
            ch.append((by_cid[cid]["start"] + t, title))
        else:
            ch.append((by_cid[cid]["start"], title))
    for t, title in ch:
        out.append(f"{mmss(t)} {title}")
    out += ["```", ""]

    short = [(mmss(a), t) for (a, t), (b, _) in zip(ch, ch[1:] + [(total, "")])
             if b - a < 10]
    out.append(f"*{len(ch)} chapters, first at 0:00, "
               f"{'all ≥10s' if not short else 'SHORT: ' + str(short)}.*")
    out += ["", "## Scenes", "",
            "| # | scene | start | dur | beats | beats/s |",
            "|---|---|---:|---:|---:|---:|"]
    tb = 0
    for i, s_ in enumerate(scenes, 1):
        b = beats(s_["cid"]); tb += b
        out.append(f"| {i} | `{s_['cid']}` | {s_['start']:.3f} | {s_['dur']:.3f} "
                   f"| {b} | {b / s_['dur']:.2f} |")
    out += ["", f"**{tb} authored beats, {tb / total:.2f}/s.** Authoring aid only "
            "— an authored tween is not a rendered pixel change. "
            "`check-cadence.py --longform` on the real render is what answers cadence.", ""]
    (ROOT / "STORYBOARD.md").write_text("\n".join(out) + "\n")
    print(f"STORYBOARD.md  {len(scenes)} scenes, {len(ch)} chapters, {tb} beats")


if __name__ == "__main__":
    main()
