#!/usr/bin/env python3
"""Generate STORYBOARD.md by READING index.html and the scene files.

A storyboard whose timing table was hand-edited stops being trustworthy the
moment one real timing changes and the doc isn't re-synced. This derives every
number from the composition itself, so re-running it after any retime is the
whole update.
"""
import re
import sys
from pathlib import Path

INTENT = {
    "01-hook":      "The word on the bottle is not the evidence.",
    "02-what":      "It's a delivery particle — and its source varies.",
    "03-evidence":  "Human evidence is real but thin, and often confounded.",
    "04-questions": "Three questions to ask before buying.",
    "05-claim":     "“Exosome technology” is a claim, not a result.",
    "06-close":     "One specific action; hands into the end card.",
    "07-endcard":   "Channel end card — 습 mark; loops back to scene 1.",
}
GROUND = {"01-hook": "paper", "02-what": "ink", "03-evidence": "paper",
          "04-questions": "ink", "05-claim": "paper", "06-close": "paper", "07-endcard": "paper"}
MECH = {
    "01-hook": "full-bleed plate + Ken Burns (new)",
    "02-what": "SVG vesicle release + TermDefinition lockup (adapted)",
    "03-evidence": "EvidenceMeter, 2 of 4 nodes (adapted)",
    "04-questions": "QuestionGate (built new → harvested)",
    "05-claim": "SplitCompare, horizontal bisector (adapted)",
    "06-close": "lockup + CTA + channel mark (new)",
    "07-endcard": "brand end card — 습 mark, wordmark, CTA (new)",
}


def main():
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    idx = (root / "index.html").read_text()

    dur = float(re.search(r'id="root"[^>]*data-duration="([\d.]+)"', idx).group(1))
    scenes = re.findall(
        r'data-start="([\d.]+)"\s+data-duration="([\d.]+)"\s*\n?\s*data-composition-id="([^"]+)"', idx)
    vo = re.findall(r'id="vo-(\d+)"[^>]*data-start="([\d.]+)" data-duration="([\d.]+)"', idx)
    sfx = re.findall(r'id="sfx-([^"]+)" src="assets/sfx/([^"]+)" data-start="([\d.]+)" data-duration="([\d.]+)"', idx)
    caps = re.findall(r'id="cap-(\d+)" class="clip vo-caption" data-start="([\d.]+)" data-duration="([\d.]+)"', idx)

    L = []
    L.append("# STORYBOARD — exosome-label-decode\n")
    L.append("**Generated by `scripts/build-storyboard.py` from `index.html`.** Do not")
    L.append("hand-edit: re-run it after any retime instead. Every number below is read")
    L.append("from the composition, not estimated.\n")
    L.append(f"- **Runtime:** {dur:.3f}s · 1080×1920 · 30fps")
    L.append(f"- **Scenes:** {len(scenes)} · **VO lines:** {len(vo)} · "
             f"**SFX cues:** {len(sfx)} · **Caption cues:** {len(caps)}")
    L.append("- **Transitions:** hard cuts at every boundary (grounds alternate; a")
    L.append("  crossfade across a ground change gives a muddy midpoint)\n")

    L.append("## Scenes\n")
    L.append("| # | Scene | Start | End | Dur | Ground | Intent | Mechanism |")
    L.append("|---|---|---|---|---|---|---|---|")
    for i, (s, d, cid) in enumerate(scenes, 1):
        s, d = float(s), float(d)
        L.append(f"| {i} | `{cid}` | {s:.3f} | {s+d:.3f} | {d:.3f} | {GROUND.get(cid,'')} | "
                 f"{INTENT.get(cid,'')} | {MECH.get(cid,'')} |")

    L.append("\n## Voiceover\n")
    L.append("Kimberly (Higgsfield `seed_audio`, element `674b71b8-…`). Durations are")
    L.append("MEASURED from the final takes — scene timing is derived from them, never")
    L.append("authored ahead of them.\n")
    L.append("| Line | Start | End | Dur | Sits in |")
    L.append("|---|---|---|---|---|")
    for n, s, d in vo:
        s, d = float(s), float(d)
        owner = next((c for (ss, dd, c) in scenes
                      if float(ss) <= s < float(ss) + float(dd)), "?")
        L.append(f"| {n} | {s:.3f} | {s+d:.3f} | {d:.3f} | `{owner}` |")

    L.append("\n## Caption cues\n")
    L.append(f"{len(caps)} burned-in cues in the reserved lane at y 1360–1520, plus the")
    L.append("sidecar `.srt`/`.vtt` — both generated from one table in")
    L.append("`scripts/build-captions.py`, so they cannot drift apart.\n")
    durs = [float(d) for _, _, d in caps]
    L.append(f"- shortest **{min(durs):.3f}s**, longest **{max(durs):.3f}s** "
             f"(floor 1.00s, max 2 lines / 6 words per line — asserted at build time)\n")

    L.append("## SFX spotting\n")
    L.append("| Cue | File | Start | Dur | End |")
    L.append("|---|---|---|---|---|")
    for cid, fn, s, d in sfx:
        s, d = float(s), float(d)
        L.append(f"| `{cid}` | {fn} | {s:.3f} | {d:.3f} | {s+d:.3f} |")
    L.append(f"\nEvery cue ends inside the {dur:.3f}s runtime (asserted in")
    L.append("`scripts/build-audio.py`); track indices are auto-assigned so no two")
    L.append("overlapping cues share a track.\n")

    (root / "STORYBOARD.md").write_text("\n".join(L) + "\n")
    print(f"STORYBOARD.md: {len(scenes)} scenes, {len(vo)} VO, {len(sfx)} SFX, "
          f"{len(caps)} captions, runtime {dur:.3f}s")


if __name__ == "__main__":
    main()
