#!/usr/bin/env python3
"""Generate index.motion.json -- declared motion intent, checked by `check`.

Sits between a source-level beat map and a full render: it is evaluated
against the SAME seeked timeline the renderer drives, so it catches an
entrance that never happens or a hold that goes dead, without paying for an
MP4. Ported from videos/ectoin-normal-person/scripts/build_motion.py; see that
file for the schema note (FLAT with an explicit `kind`, verified against
hyperframes@0.8.22's own validator, NOT the nested {"appearsBy": {...}} form).

SCOPE: the root-scoped `keepsMoving` cadence ceiling plus every `appearsBy`
assertion this project's plan calls HARD (see PLAN's Verification section,
item 4): 09-exclusion's ground inversion, 07's question mark, 21's verdict
box, 28's two negation voids, 29's closing question, and 01's "bacteria"
span -- all authored with real @w()/@first bindings in
build_frames.py/frames_a27.py.

Four rules ported unchanged from the sibling, still true here:

  1. ONE sidecar, at the PROJECT ROOT. `check` looks for it beside the root
     composition; one written next to a sub-composition is silently ignored.
  2. `keepsMoving` is scoped to #root, NEVER to a scene -- a per-scene selector
     reports that scene's OFF-SCREEN time as frozen and fails by construction.
  3. `maxStaticSec` comes from this format's cadence budget (long-form, 6.0s).
  4. Assertions name COPY ELEMENTS, not their containers.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
from timing import walk

# (scene cid, selector, human note, lead seconds before the offset given).
# Selector is the element's OWN id (no id-prefixing pass exists in this
# project's _preamble.py -- ids are emitted as authored, unlike the sibling).
COPY = [
    ("09-exclusion", "#m-h", "the ground-inversion headline -- must appear "
                              "at or after the clip-path sweep begins"),
    ("07-question",  "#s7-q", "the act's closing question"),
    ("21-verdict",   "#v-box", "the verdict panel, bound to \"Promising\""),
    ("28-remember",  "#nx-0", "the first negation void, bound to \"Not\" (1st)"),
    ("28-remember",  "#nx-1", "the second negation void, bound to \"Not\" (2nd)"),
    ("29-cta",       "#c-q", "the closing question, bound to \"would\""),
    ("01-hook",      "#s1-bacteria", "the hook's \"bacteria\" span"),
]


def main():
    scenes, total = walk()
    by_cid = {s.cid: s for s in scenes}

    asserts = []
    for cid, sel, note in COPY:
        s = by_cid[cid]
        # bySec is ROOT-ABSOLUTE (the renderer seeks the whole composition,
        # not this scene's own sub-timeline) -- confirmed the hard way: a
        # scene-local bound here read as "must be visible by root t=9.65s",
        # which scene 07 (starting at root t=56.9s) can never satisfy.
        asserts.append({
            "kind": "appearsBy", "selector": sel,
            "bySec": round(s.start + s.dur, 2),
            "note": f"{cid}: {note}",
        })

    asserts.append({
        "kind": "keepsMoving", "withinSelector": "#root", "maxStaticSec": 6.0,
        "note": "long-form cadence ceiling. Root-scoped on purpose: a "
                "per-scene selector reports a scene's off-screen time as frozen.",
    })

    spec = {
        "$comment": "Generated by scripts/build_motion.py -- do not hand-edit. "
                    "check discovers this automatically; there is no --motion flag.",
        "duration": total,
        "assertions": asserts,
    }
    (ROOT / "index.motion.json").write_text(json.dumps(spec, indent=2) + "\n")
    print(f"index.motion.json: {len(asserts)} assertions "
          f"({len(COPY)} appearsBy, 1 keepsMoving)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
